### PR TITLE
[DOCS] Update datepicker internationaization example

### PR DESCRIPTION
**Pull request by Draykee**
## Summary
Updated the datepicker internationalization example in the documentation.

* What is the change?
Added codesnippets to show how to register the data of a locale and how to use  `LOCALE_ID ` to change the date format of the DatePicker

* What is a use case for this change?
Prevent errors while changing the locale

### CODE REVIEW

**Comment by gnomeontherun** [comment]
Looks like a small lint error, can you check @Draykee?

**Comment by Draykee** [comment]
Sorry I couldn't run the test:format scripts to find the error. 
I'm not even sure if it's just an lint error ==> https://travis-ci.com/vmware/clarity/jobs/203675712

**Comment by gnomeontherun** [comment]
Its a very small issue, for some reason you have an extra whitespace ` ` at the end of the line `provideLocaleExample = PROVIDE_LOCALE_EXAMPLE;`. Our precommit hooks should have run the formatter for you, but sometimes if you use an IDE or have a special setup those don't get run.

**Comment by coryrylan** [comment]
Thanks for adding this!

**Pull request merged**
