### PR TITLE
[DOCS] Update datepicker internationaization example

### PR DESCRIPTION
**Pull request by Draykee**
## Summary
Updated the datepicker internationalization example in the documentation.

* What is the change?
Added codesnippets to show how to register the data of a locale and how to use  `LOCALE_ID ` to change the date format of the DatePicker

* What is a use case for this change?
Prevent errors while changing the locale

### CODE REVIEW

**Comment by Draykee** [comment]
Guess I need a littlebit of help here. It's still not signed after setting: user.name, user.email and the GPD keys. What am I missing?

**Comment by gnomeontherun** [comment]
Ok sorry, I didn't mean to close this. I tried to change the branch and GitHub just closed it. Could you make a new PR to `master` instead with these changes?

**Comment by Draykee** [comment]
Please correct me if I'm wrong:
I will make the changes directly on the master branch and not on the website branch?!

**Comment by gnomeontherun** [comment]
That is correct, the website branch is for 0.13 and older, and 1.0+ is part of master.

**Comment by Draykee** [comment]
Okay good to know! Therefore https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md#contributing-to-documentation should be updated too :)

**Pull request closed without merging**
