### PR TITLE
Basic implementation for Combobox

### PR DESCRIPTION
**Pull request by Wallabeng**
As we need this Combobox in our project, I implemented the basics for it.
I know the normal way for contributing a whole component should be more structured and discussed before implementation, but as we need it soon I gave it a shot.
As component design I took #248 

This implementation handles frontend-driven data only.
So from design #248 following topics are completed:
- Default view
- Active view
- Selections
- Typing
- Additionally: Keyboard selection with "up" and "down" keys and "enter" as selection

Please let me know if this implementation is something contributable.
If it looks good in general, I start writing more tests (otherwise it's just a waste of time).

Signed-off-by: Wallabeng <marcel@ring-mail.at>

### CODE REVIEW

**Comment by youdz** [comment]
Hi @Wallabeng, thanks for the contribution. I briefly started looking at your changes, and quickly realized I was lost in the code because this is a component we merged in incomplete and do not maintain, so we haven't even looked at it for months. I'll need to get back up to speed on it first before I can properly review this, which will take me a bit of time.
And I'm guessing my teammates are in the same situation.

I just wanted to post this to make sure you knew we are not ignoring this PR, just needing some time to post our first comments on it. Thanks. 🙂

**Comment by mathisscott** [comment]
@youdz 
Where are we on this PR?

**Comment by youdz** [comment]
Looks like my comments are sitting there “Pending”, my bad. I’m on my phone, but I’ll try to submit them right now.

**Comment by youdz** [comment]
We reviewed this with the team, and decided to assign Combobox to a team member given the complexity of the component. @jeeyun has started working on it, so I will close this PR. She may look at this for some pieces, in which case we can still chat on this closed PR if she has questions.

Thanks for the contribution, even if it didn't make it through as is.

**Pull request closed without merging**
