### PR TITLE
[NG] use tilde to import bootstrap scss

### PR DESCRIPTION
**Pull request by gjungb**
replace node_modules folder with ~ for more flexibility

 Signed-off-by: Gerd Jungbluth <gerd.jungbluth@engawa.de>

### CODE REVIEW

**Comment by hippee-lee** [comment]
Thanks for the contribution @gjungb.

You can sign your commit and repush with the following:
```
git commit --amend --author "NAME SURNAME <email>
```

Also, when you commit something and need to sign it, you can do it automatically with 
the **-s, --signoff         add Signed-off-by:** option
```
$ git commit -s 
```

**Comment by gjungb** [comment]
@hippee-lee Hi, I am bit stuck here. How do I sign the three commits retrospectively? Or should I open a new pull request? Thx

**Comment by gnomeontherun** [comment]
@gjungb The best thing is to squash them into one commit, and sign it. There are plenty of posts about how to do this, such as http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html. This allows you to combine the three commits, and then edit the commit message for sign-off requirements.

**Comment by adityarb88** [comment]
Closing this PR because the dco is required to be merged into master. Duplicate PR here: https://github.com/vmware/clarity/pull/2021

Thanks for the contribution!

**Comment by gjungb** [comment]
@adityarb88 Thx 👍

**Pull request closed without merging**
