### PR TITLE
WEB Updating docs for datagrid selection

### PR DESCRIPTION
**Pull request by bdryanovski**
Update example for datagrid

fixes: #2006

### CODE REVIEW

**Comment by Jinnie** [comment]
Please make sure if this needs to be fixed in other versions too

**Comment by coryrylan** [comment]
Looks like that bug is in the 0.12x version of the docs as well.

**Comment by bdryanovski** [comment]
@Jinnie - I will be happy to document that part as well.  But will need some help on how to rebuild part.
@coryrylan - done

**Comment by bdryanovski** [comment]
I manage to find how to update the cache;

I gonna leave this here for my future self:
```bash
$ cd v0.VERSION/
$ npm install
$ npm run deploy:ci
$ cd ..; cp -a deploy/documentation/v0.VERSION/** v0.VERSION-cache
```

I'm not quite sure why there is no cache directory for `v0.12` & `v0.13`

**Comment by Jinnie** [comment]
Because .12 and .13 used to be updated rather frequently (when 1.0 and 2.0 were not around). And caching .10 and .11 was speeding the build process.
Now 1.0 and 2.0 follow absolutely different deployment process, so we can say that all 0.x are sort of "cached" inside the old process.

**Comment by bdryanovski** [comment]
It seems that this is no longer the valid case so I'm closing it.

**Pull request closed without merging**
