### PR TITLE
[NG] Allow property shortcut for clrDgSortBy

### LINKED ISSUE #1089: Allow property shortcut for clrDgSortBy
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

It would be nice if the `[clrDgSortBy]` input for datagrid columns also accepted a string describing the property name on the items to use when sorting. Exactly like `[clrDgField]`. It should still accept a comparator too.
This means that if the given input is a string, we create the default property comparator for it, otherwise we just use the given comparator.

### Actual behavior

Currently, `[clrDgSortBy]` only accepts a comparator. There are a few use cases where you need the "property shortcut" but don't want filtering on the column itself.

### PR DESCRIPTION
**Pull request by chunghha**
Fixes #1089

Signed-off-by: Chris Ha <chunghha@users.noreply.github.com>

### CODE REVIEW

**Comment by chunghha** [comment]
Please check the failure of signpost left-top test which is not related to this change.

**Comment by chunghha** [comment]
Add example for property shortcut for clrDgSortBy.

**Comment by chunghha** [comment]
Add tests per review. Let me know if good for squashing.

**Comment by chunghha** [comment]
Thanks, @youdz 

Squashing done. But, signposts left-top [chrome] test failed again.
https://travis-ci.org/vmware/clarity/jobs/248391008

Please take a look and let me know if I need to do anything on the failed test.

**Comment by hippee-lee** [comment]
Hi @chunghha - Give me a few minutes. I'm looking now and will get you an updated image if it needs one.

**Comment by hippee-lee** [comment]
@chunghha - updated the reference image for the gemini top-left signpost test. I am attaching a zip with a folder named `top-left`. In the folder is the reference image for that test.

Can you replace the **`<clarity-fork>/gemini/screens/signposts/top-left`** folder with the one in the attached archive? I believe this should take care of the failing gemini test. 

Please let me know if you have any questions or issues. 
[left-top.zip](https://github.com/vmware/clarity/files/1112970/left-top.zip)

**Comment by chunghha** [comment]
@hippee-lee I thought you meant left-top folder. Looks all tests are OK now. Do I need to squash again?

**Comment by chunghha** [comment]
@hippee-lee all passed now.

**Comment by hippee-lee** [comment]
Thanks for doing this.

**Pull request merged**
