### PR TITLE
docs(tree-view): Readded missing documentation of lazy-loading recursive trees

### PR DESCRIPTION
**Pull request by wokis**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Documentation about lazy-loading recursive trees was lost/removed.

Issue Number: N/A

## What is the new behavior?

Documentation about lazy-loading recursive trees is readded as per https://github.com/vmware/clarity/discussions/5598#discussioncomment-360379.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bbogdanov — APPROVED** [review]

**Review by hippee-lee — APPROVED** [review]
Thank you for submitting this!
lgtm.

**Comment by hippee-lee** [comment]
Hi @wokis - this is almost ready to go. There is a formatting error in one of the added files that can be fixed with the command:

```
npx prettier --write apps/website/.vuepress/code/demos/tree-view/lazy-recursive-ng.ts
```

And we need you to squash down to a single commit. Once that is done I can get this merged into the next branch.

**Comment by wokis** [comment]
I've run npx prettier and squashed the commits. Hopefully third time's the charm :)

**Comment by hippee-lee** [comment]
Awesome, thank you for the contribution!!

**Pull request merged**
