### PR TITLE
style(select): adapt invalid style of input on select element

### PR DESCRIPTION
**Pull request by twittwer**
## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [x] Other... Please describe: Adapt styles for consistency

## What has changed?

| Before | After |
| ------ | ----- |
| image | image

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by hippee-lee** [comment]
Thanks for this. The travis build is failing because the reference images need to be updated with this change. These two commands should handle it for your:

- npm run gemini:fix:light set2
- npm run gemini:fix:light set3

**Comment by twittwer** [comment]
Thx, for the tip - I fix it tomorrow

**Comment by twittwer** [comment]
> Thanks, this was on my list to get back to fixing! We can also do the cleanup on the visual testing on our end if you need us to.

I'm having some trouble to get it running on my machine - so it would be nice, if you can do it 🙂

**Comment by hippee-lee** [comment]
@twittwer - I can do it for you. Our options are as follows:
1) give me permission to push to your repo so that I can push the change and amend your commit with the new reference images
2) I can close this PR,  take your commit and create a new branch with it at the head, then generate the new images and amend the commit there. This also means I would have to open a new PR with those changes.

Do you have a preference?

**Comment by twittwer** [comment]
@hippee-lee Thx, I added you as collaborator (option 1)

**Pull request merged**
