### PR TITLE
[web] add icon download function

### LINKED ISSUE #3044: Icon download shows sources code instead of direct download
## Describe the bug

When downloading icons from the Clarity website, it shows SVG source code instead of allowing users to get the SVG file into their local machine.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to 'https://clarity.design/icons'
2.  Click on any icon on the page
3.  Click on 'SVG ICON' button
4.  See SVG code 

## Expected behavior

SVG file gets downloaded onto the client machine.

## Versions

**App**

* Angular: n/a
* Node: n/a
* Clarity: n/a

**Device:**

* Type: MacBook
* OS: macOS Mojave Version10.14.2
* Browser : Chrome
* Version 71.0.3578.98

### PR DESCRIPTION
**Pull request by gnomeontherun**
This updates the website to now have a netlify function for downloading the icon files directly from github raw urls. GitHub doesn't set the Content-Disposition header for download of the binary, so this basically proxies the call to do that for you. It also updates the website to build the URL to the icon function.

fixes #3044

### CODE REVIEW

**Comment by ChitMeng-VMware** [comment]
When I tried to download again. The status is "Failed - No file". I am using Chrome, Version 71.0.3578.98 (Official Build) (64-bit) on MacOS Mojave.

**Comment by gnomeontherun** [comment]
The deployment is still pending, please try again later.

**Comment by gnomeontherun** [comment]
@ChitMeng-VMware It should be working, can you confirm?

**Comment by ChitMeng-VMware** [comment]
Yes it worked. Thank you.

**Pull request merged**
