### PR TITLE
fix(btn-group): change to overflow:hidden for :focus style

### LINKED ISSUE #5446: btn-group class affects inner buttons' on-focus style due to its { overflow: visible } style property
## Describe the bug

btn-group class affects inner buttons' on-focus style due to its { overflow: visible } style property

Not particularly an accessibility issue, the focus of the buttons inside a btn-group does work, 
but it is not styled properly.

Screenshot 2021-01-14 at 13 00 25

## How to reproduce

Refer to the clarity documentation for Button Group and reproduce there by  focusing on the examples with a "tab".
Observe the curly style of a button when focused, which should be a rectangle instead: 
https://clarity.design/documentation/button-group 

## Expected behavior

The style of a focused button should be a rectangle.

## Local fix

Locally, until this bug is resolved,
I have fixed it by overwriting clr's style for the inner buttons under a btn-group with
`{ overflow: hidden }
`
## Versions

**App**

- Angular: [e.g. 6]
- Node: 14
- Clarity: [e.g. 0.12.5]

**Device:**

- Type:  MacBook
- Browser  chrome

### PR DESCRIPTION
**Pull request by royling**
Closes #5446 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #5446 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bbogdanov** [comment]
@royling Thank you for submitting a PR for this issue.

Could you please try this fix on button with larger content in it?

Like 

`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy`

There are teams that use the outline buttons with larger content and this change might affect them.

**Comment by royling** [comment]
@bbogdanov I tried the scenario within https://clarity-light-theme-v5-ycnaky.stackblitz.io/, do you think the issue is fixed?

I did notice that the behavior for the button in a button group diffs from a single outline button.
If the expectation is to make the button group behave as the same as single button, the `overflow:hidden;` style needs to be applied to `.btn-group .btn` as well. That's like:

```css
.btn-group .btn, .btn-group .btn:focus {
  overflow: hidden;
}
```

**Comment by Jinnie** [comment]
I would be worried if we have one behavior with focus and different without it. So, IMO, an unconditional `overflow:hidden `should be the best. It's interesting, that even if we add `overflow-y:hidden`, it still has effect on the x-axis overflow and activates the `text-overflow: ellipsis` which otherwise stays inactive.

**Comment by royling** [comment]
> an unconditional overflow:hidden should be the best.

totally agree. Then the button in a group behaves the same as a single button.

**Comment by royling** [comment]
updated the fix accordingly.

**Comment by Jinnie** [comment]
Trying to find out why the tests are failing. Sorry for the delay.

**Comment by royling** [comment]
> Trying to find out why the tests are failing. Sorry for the delay.

I even could not retry it, either...

**Comment by bbogdanov** [comment]
@royling Can you please pull the latest changes in the `next` branch? We did a fix for the build issue you are facing two days ago

**Comment by royling** [comment]
> @royling Can you please pull the latest changes in the `next` branch? We did a fix for the build issue you are facing two days ago

will do it soon.

**Comment by royling** [comment]
Thanks @bbogdanov, now the build is ok!

**Review by Jinnie — APPROVED** [review]

**Review by bbogdanov — APPROVED** [review]

**Pull request merged**
