### PR TITLE
feat(datagrid): Add API/Configuration for disabling direct page acces…

### PR DESCRIPTION
**Pull request by nvladimirovi**
…s in datagrid pagination

Add new input parameter to clr-dg-pagination
component to provide the ability to disable the
current page input.

Signed-off-by: Nikola Vladimirov Iliev <nvladimirovi@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?
Issue Number: 4233

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by gnomeontherun** [comment]
@colinreedmiller I'm tagging you Colin so we can review this quickly, just to be sure design is happy with this.

**Comment by Jinnie** [comment]
Just adding a bit more context. As explained on the main issue #4233, during an Office Hours session with the vCD team, we verified that the exposed case is valid:
- Due to technical reasons, the backend API only allows changing to "first", "last", "next" or "previous" pages and NOT to an arbitrary page.
- The API can not be changed.
- They still need the ordinary footer pagination but with text "2/3" instead of input field "[2]/3".
- First, last, next, prev controls remain unchanged.

**Comment by colinreedmiller** [comment]
The only concern I'd have would be if the user would be confused "Why can't I change the page by inputting a number in this field?" This appears to not be a problem since the input for arbitrary page number: [#] / # 
is styled # / # (not an input).
If this understanding is correct then this is UX ready.

**Comment by gnomeontherun** [comment]
This doesn't have a working demo to preview without pulling it down myself and running it, usually we need a demo in our dev app to see this behavior in action.

**Comment by Jinnie** [comment]
Hi @gnomeontherun, Nikola was so kind to quickly provide the requested addition to the dev-app page:
https://5e395d1f52ce1bf69ca93685--vmware-clarity.netlify.com/datagrid/pagination
Looks as described and expected. I proceed with merging and back-porting it to n-1.

**Pull request merged**
