### PR TITLE
fix(core:layout): remove line height erasure when disabled

### PR DESCRIPTION
**Pull request by ashleyryan**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #6135 

## What is the new behavior?

No more cutting off the top of the label

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mathisscott — APPROVED** [review]

**Review by hippee-lee — APPROVED** [review]

**Review by bbogdanov — CHANGES_REQUESTED** [review]
Thank you for the contribution!

Could you please update the commit message to fix(core:layout): remove line height erasure when disabled?

Thank you in advance!

**Comment by ashleyryan** [comment]
Sure @bbogdanov, updated!

**Review by bbogdanov — APPROVED** [review]
Thank you!

**Comment by mathisscott** [comment]
Thank you, @ashleyryan !

**Pull request merged**
