### PR TITLE
[ICONS] fixed icon color issue and created tests

### LINKED ISSUE #426: Icon 'tag' does not paint with the CSS font color
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
the code below should paint the 'tag' clarity-icon in white.

### Actual behavior
the code below paints the 'tag' clarity-icon in black.

### Reproduction of behavior
HTML:
`
<clr-icon shape='tag' class='my-icon'></clr-icon>
`

CSS:
`
.my-icon{
  color: #fff
}
`

See screenshot attached:
screen shot 2017-01-27 at 3 17 53 pm

### Environment details

* **Clarity version:** 
0.8.4

### PR DESCRIPTION
**Pull request by Shijir**
Fixes #426 

Tested: Chrome, Safari, Firefox, IE10

Signed-off-by: Shijir Tsogoo <stsogoo@vmware.com>

### CODE REVIEW

**Comment by Shijir** [comment]
Default:
normal

With `has-alert` class:
outline-has-alert

With `has-badge` class:
outline-has-badge

With `is-solid` class:
solid

With `is-solid` and `has-alert` classes:
solid-has-alert

With `is-solid` and `has-badge` classes:
solid-has-badge

Icon color should match the context color. For example, having `color: #31b0d5;` on parent element produces:

filled-by-context-color

**Comment by Shijir** [comment]
@mathisscott it's been always yellow unless `--error` is attached to `has-badge` class. 

screenshot 2017-02-01 08 12 35

This code snippet below is the (commit)[https://github.com/vmware/clarity/blob/79ddfab87242bfc24e1f2701e5f6b44c20ca49da/src/clarity-icons/clarity-icons.scss] that has introduced the icon variants. 


```
    &.has-badge--success {
        .clr-i-badge {
            @include setIconColor($clr-icon-color-success);
        }
    }
    &.has-badge--error {
        .clr-i-badge {
            @include setIconColor($clr-icon-color-error);
        }
    }
    &.has-badge--info {
        .clr-i-badge {
            @include setIconColor($clr-icon-color-info);
        }
    }
    &.has-alert {
        .clr-i-alert {
            @include setIconColor($clr-icon-color-warningYellow);
        }
    }
```

Unlike `has-alert`, we didn't specify the default color of a badge when `has-badge` class is used without extra suffixes such as `--error`, `--info`, etc. If we had one, that would look like this:

```
&.has-badge {
        .clr-i-badge {
            @include setIconColor($clr-icon-color-error); 
        }
    }
```

**Comment by Shijir** [comment]
Hi @mathisscott, the default icon badge color is fixed please checkout.
outline-has-badge
solid-has-badge

**Comment by mathisscott** [comment]
Great job with the preview toggles. Looks great. I think users are going to like that a lot.

**Comment by lil-kim** [comment]
Sorry I'm late to the party. Just wanted to say the page looks great and I love the toggle!

**Pull request merged**
