### PR TITLE
chore: update to Angular 11.2.5 and Ivy distribution mode

### PR DESCRIPTION
**Pull request by sis0k0**
Signed-off-by: Stanimira Vlaeva <stanimira.vlaeva@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gnomeontherun** [comment]
I want us to put a hold on merging this just yet. We might have a tactical reason to change how we merge this.

**Comment by sis0k0** [comment]
@gnomeontherun, can we remove the `Blocked` label as we discussed in person? This is an update to a minor Angular version (11.2) and not to a major one (v12).

**Comment by gnomeontherun** [comment]
yeah we can move forward

**Comment by coryrylan** [comment]
Do we want this in the next release?

**Review by coryrylan — APPROVED** [review]

**Review by bdryanovski — APPROVED** [review]
LGTM

**Comment by sis0k0** [comment]
@coryrylan, I think this can wait until the next release. I'll merge it after today's release :)

**Pull request merged**
