### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by joneff**
## PR Type

What kind of change does this PR introduce?

- [X] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Fixing a typo.

### CODE REVIEW

**Review by coryrylan — APPROVED** [review]

**Review by mathisscott — APPROVED** [review]

**Comment by mathisscott** [comment]
@joneff 

All you need to do is amend your commit message so that your name and email are the last line of the commit like so...

`chore: fix typo

Signed-off-by: Joneff <your.email@email.org>`

More guidance here:

https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

https://www.educative.io/edpresso/how-to-change-a-git-commit-message-after-a-push

**Comment by hippee-lee** [comment]
@joneff - If you are able to amend the commit and push the update I'll merge this in asap. If it isn't something you can do, let me know and I'll adopt the PR and make the update for you in a separate PR.

**Comment by joneff** [comment]
Sorry about that. I will do it

**Comment by joneff** [comment]
@hippee-lee I used my real email address and @vmwclabot is still complaining. Ideas?

**Comment by bdryanovski** [comment]
@joneff I think that the issue here is that you just need to have a body of the commit and the email is not the same as the account from which the commit is made.

```txt
chore: fix typo

 - fix typo in the documentation

Signed-off-by: joneff <joneff@users.noreply.github.com>
```

Thanks again for finding and fixing the typo :)

**Comment by joneff** [comment]
@bdryanovski tried and didn't work.

**Comment by hippee-lee** [comment]
@joneff - It looks like you have to update both the commit and the commit message. It looks like the commit ([patch file here](https://patch-diff.githubusercontent.com/raw/vmware/clarity/pull/6428.patch)) was signed with the no reply email. You should be able to fix both the patch file and the commit message by running:

```git commit --amend --author "Jon Eff <joneff@gmail.com>"```

I am guessing for your real name / real email so put the correct info in there ...Give that a shot and let me know if it helps.

**Comment by joneff** [comment]
@hippee-lee it worked!

**Comment by hippee-lee** [comment]
Thank you @joneff - we appreciate your help!
I will merge after the build finishes running.

**Pull request merged**
