### PR TITLE
[feature request] Add a Search component

### PR DESCRIPTION
**Pull request by varticvasile**
#186

initial commit to be reviewed

Signed-off-by: Vasile Vartic <vasile.vartic@bytex.ro>

BY BYTEX ROMANIA

### CODE REVIEW

**Comment by jaffoneh** [comment]
@varticvasile could you provide some screenshots of how this works. @reddolan is currently working on the design specs for search, maybe we can work together on getting that moving? Thanks for your contribution and looking forward to collaborating with you on this!

**Comment by dragosrusu** [comment]
I think @varticvasile implemented a demo page. Maybe test there.
At this stage we should worry about functionality. Look and feel can be easily changed.

**Comment by youdz** [comment]
Thank your for trying to implement a first draft of this component, @varticvasile.

First of all, I recommend you read our [coding guidelines](https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md). Will cannot accept contributions that do not respect these.

In light of this, here are a few examples of things that would need to change. This list is not exhaustive, there might be other details in the code that might need to be fixed, but I just want to show examples from the coding guidelines rules.
- You need to add ARIA attributes to make sure this component is accessible. See https://www.w3.org/TR/wai-aria/roles#combobox and
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role. Also implement the keyboard shortcuts required in these specs.
- This use case is too narrow, we want to offer full customizability from the beginning. In this case, at least support a custom filtering function, custom display of results, and non-string data (typically objects).
- Use projection for displayed results (after previous point).
- Support ngModel for even better customizability an integration. I see you started that based on commented out imports, you were right to try it, it's the way to go.
- Add the "clr" prefix to all inputs/outputs. See our other components.

Finally, I don't understand the point of the demos with no data. It's literally an `<input type="text">`.  All you are exposing is a `[placeholder]` input, a `[(value)]` to-way binding and a `(change)` event, all of which are already natively offered by inputs. So the only reason to use this component is for the results dropdown.

I like the idea of supporting regexes for power users, you wrote plenty of tests, and you even took the time to write a demo. Good initiative on these.

**Comment by jaffoneh** [comment]
Based on the final comment by @youdz and no additional updates. I am closing this pull request, please let me know in a comment if you think it should be reopened and provide more information.

For big components like this with a big code contribution, we should discuss first a set of APIs that we agree on and a technical spec in order to match what we're looking to implement within Clarity.

Thanks again for making the contributions and please do take a look at open issues, open new components, and feel free to bring up any places where you can contribute. We're grateful for our community and contributors.

**Pull request closed without merging**
