### PR TITLE
[ICONS] publish icon svg files

### LINKED ISSUE #386: Add a link for downloading the SVG icons
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Link to download the all of the SVG icons (and variants) 
[icons_vol1-2_svg.zip](https://github.com/vmware/clarity/files/733121/icons_vol1-2_svg.zip)

Link to read: Download all SVG icons (and variants)

### Actual behavior
no way exists for users to download the existing SVG icons

### Reproduction of behavior
image

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

### PR DESCRIPTION
**Pull request by Shijir**
- Fixes #386

Signed-off-by: Shijir Tsogoo <stsogoo@vmware.com>

### CODE REVIEW

**Comment by Shijir** [comment]
[core-shapes.zip](https://github.com/vmware/clarity/files/752019/core-shapes.zip)
[essential-shapes.zip](https://github.com/vmware/clarity/files/752018/essential-shapes.zip)
[social-shapes.zip](https://github.com/vmware/clarity/files/752016/social-shapes.zip)
[technology-shapes.zip](https://github.com/vmware/clarity/files/752017/technology-shapes.zip)

**Comment by Shijir** [comment]
clarity

**Comment by jaffoneh** [comment]
@Shijir do we have a "download all" link or do I have to download each specific group?

**Comment by Shijir** [comment]
@jaffoneh currently, it allows users to download these sets individually. And it reflects the changes coming to our iconography website that have been presented in Yen's sketch files.

**Comment by jaffoneh** [comment]
@Shijir I think it might make sense to have a download all link as well. CC @yenmade and @mathisscott

**Comment by Shijir** [comment]
@jaffoneh @mathisscott @yenmade What are your thoughts on this:
clarity

**Comment by jaffoneh** [comment]
@Shijir I would assume it goes at the very top but @yenmade will be able to provide more feedback.

**Comment by Shijir** [comment]
@jaffoneh, I like this one. How do you like it? @yenmade came up with this:
clarity

**Comment by Shijir** [comment]
clarity

**Comment by reddolan** [comment]
Is there a reason why the download button is so far down the page? I think the download button needs to be at the top of the page. It is likely going to be one of the most commonly used/searched for things when it comes to Icons. Having it midway down the page makes people have to hunt for it.

**Comment by mathisscott** [comment]
@yenmade, @jaffoneh, and I felt it would be best to put it towards the bottom of the page so as not to confuse people. The SVG download is for design. We felt having it towards the top of the page would lead users to believe that the icon system was just a folder of SVGs.

**Comment by reddolan** [comment]
Gotcha, a valid concern. The way the button is labeled right now could cause confusion. If it were labeled "Download All Icons" I think it would be less confusing. 

I still stand by my previous comment about this being a higher priority item for users, even if it might be used more by designers. I also don't think it is fair to single out a certain type of user in this way. If we have concerns about confusing developers by having the link at the top, then we need to work on the content to explain that, not push a highly important object to the bottom of a page.

**Comment by jaffoneh** [comment]
@reddolan the location of the button is currently temporary considering we're working on a complete re-design of the icons page for the new website. We just wanted to offer the download button ASAP even before the new website.

**Comment by reddolan** [comment]
@jaffoneh thank you for the reminder. Hopefully it still has a prominent location in the new design

**Pull request merged**
