### PR TITLE
docs(react): update react docs with testing note

### PR DESCRIPTION
**Pull request by ashleyryan**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by ashleyryan** [comment]
This is unrelated to this PR, but when I had the file open, I noticed that the ref section was out of date. I believe @coryrylan mentioned awhile back that that API was going to be changed (and it has, I can't get that code example to work). 

I was going to update to use a function component example (instead of a class component), but the description above the code example isn't accurate anymore, and some of the types are weird: https://codesandbox.io/s/goofy-sun-p945c?file=/src/App.tsx

**Review by mathisscott — APPROVED** [review]
LGTM. Thanks @ashleyryan !

Your PR is getting dinged by VMware's DCO bot. So you'll want to amend your commit message so that the last line is...

`Signed-off-by: Ashley Ryan <asryan@vmware.com>`

...and then push the commit back up.

**Comment by ashleyryan** [comment]
I thought I fixed that earlier, right after I saw it. Is it still yelling?

https://github.com/vmware/clarity/pull/6256/commits/5c5e159892606eb169954042d79e3c65a6037d5e

**Comment by mathisscott** [comment]
> I thought I fixed that earlier, right after I saw it. Is it still yelling?
> 

Ack! No. It's no longer giving the dco-required warning. My bad.

**Review by Shijir — APPROVED** [review]

**Comment by mathisscott** [comment]
Changes merged. Thanks, @ashleyryan !

**Pull request merged**
