### PR TITLE
[ux] iOS smoth scrolling

### PR DESCRIPTION
**Pull request by uncledent**
Improvement of scrolling experience on iOS.

Signed-off-by: Denis Beklarov <danny@delar.de>

### CODE REVIEW

**Comment by adityarb88** [comment]
@uncledent: Could you please amend your commit message to include your email in angle brackets?

image

Something like this: `Signed-off-by: John Doe <john.doe@email.org>`

**Comment by adityarb88** [comment]
@uncledent: Now it shows 3 commits instead of 1.

image

To merge, we need 1 commit with the right Sign-Off message. Could you please squash your commits?

**Comment by uncledent** [comment]
It's a kind of tricky now, I'll do it better tomorrow.

**Comment by uncledent** [comment]
Finally it should be right now..

**Comment by adityarb88** [comment]
@uncledent: Thanks a lot for the contribution! We have added your name to our community page: https://vmware.github.io/clarity/community

**Comment by uncledent** [comment]
@adityarb88 Thank you!

**Pull request merged**
