### PR TITLE
fix(datalist): layout when datalist has focus

### PR DESCRIPTION
**Pull request by derkoe**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The layout of datalist is broken, when item has focus. 

Issue Number: #5094

## What is the new behavior?

The layout is now fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bbogdanov** [comment]
LGTM

**Review by bbogdanov — APPROVED** [review]

**Comment by derkoe** [comment]
Signed off commit

**Review by Jinnie — APPROVED** [review]

**Comment by mathisscott** [comment]
@bdryanovski

**Comment by mathisscott** [comment]
@bdryanovski 

You're the release person atm. Could you merge this issue and then backport it to v4?

**Comment by bdryanovski** [comment]
Sure .. 👍

**Comment by hippee-lee** [comment]
Thanks for submitting this. There was already an issue and PR that will address this: #5053
The original issue is #5009. I'm closing this as the fix will go out in the next release.

**Pull request closed without merging**
