### PR TITLE
docs: fix typos in markdown documents

### PR DESCRIPTION
**Pull request by mcosta74**
I used the Code Spell Checked VSCode extension
* https://github.com/streetsidesoftware/vscode-spell-checker

Signed-off-by: Massimo Costa <costa.massimo@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [x] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

* [ ] Yes
* [ ] No

### CODE REVIEW

**Comment by mcosta74** [comment]
> Need to be updated as well for v1

@bdryanovski shall I create a PR for the v1 branch as well?

**Comment by Jinnie** [comment]
It would be great if you do the backport. Thanks, @mcosta74!

**Comment by mcosta74** [comment]
> It would be great if you do the backport. Thanks, @mcosta74!

Created #3786 as backport of this

**Comment by mcosta74** [comment]
@bdryanovski, you assigned this PR to me.
Is there anything else I have to do?

**Comment by Jinnie** [comment]
Nothing from you, @mcosta74 
Bozhidar assigned it for better tracking.
I see that your website deployment has stalled. Restarted it.

**Pull request merged**
