### PR TITLE
[UI] Fix for #655

### PR DESCRIPTION
**Pull request by Shijir**
- Original owner of this PR is @spadidapelli
- Resolves https://github.com/vmware/clarity/issues/655

Signed-off-by: Shijir Tsogoo <stsogoo@vmware.com>

### CODE REVIEW

**Comment by adityarb88** [comment]
Hey @Shijir. Are you satisfied with the fix? I am not sure how the icons were generated? Was the SVG taken from our website or just the color changed? If you think it doesn't completely solves the issue then we can spend more time on this or actually mark this for 0.10.0 with the `clr-icon` change. we can also check what @mathisscott thinks about this.

**Comment by adityarb88** [comment]
I will wait for the CSS Regression Images to be added to this PR before reviewing it.

**Comment by Shijir** [comment]
@lil-kim, with this PR, the alerts look like this now:
screenshot 2017-04-25 11 45 15

**Comment by Shijir** [comment]
@adityarb88 @lil-kim It looks like these changes by @spadidapelli adequately satisfy the requests made in #655. The visual diff by Gemini shows the new icons look slightly smaller than the old ones.

**Pull request merged**
