### PR TITLE
Angular separation

### PR DESCRIPTION
**Pull request by Shijir**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [x] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sis0k0** [comment]
Did we decide to leave the source of `eslint-plugin-clarity-adoption` in the `next` branch? Also, with this setup will the `schematics` source be duplicated in the `next` and `angular` branches?

**Comment by sis0k0** [comment]
I've tried using the `yarn publish:local` script after building the project with `yarn build:ci`, but I'm getting the following errors:

```
error Command failed.
Exit code: 1
Command: git
Arguments: add dist/clr-icons/package.json
Directory: /Users/svlaeva/clarity
Output:
The following paths are ignored by one of your .gitignore files:
dist/clr-icons/package.json
Use -f if you really want to add them.
```

and

```
$ node --eval "console.error('ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.\nPlease delete and rebuild the package, without compiling with NGCC, before attempting to publish.\nNote that NGCC may have been run by importing this package into another project that is being built with Ivy enabled.\n')" && exit 1
ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.
Please delete and rebuild the package, without compiling with NGCC, before attempting to publish.
Note that NGCC may have been run by importing this package into another project that is being built with Ivy enabled.
```

**Comment by sis0k0** [comment]
Chrome crashes when I try to add a comment to a specific file, so I'm adding the suggestion as a comment instead - it might be good to execute the schematics tests as part of the `yarn test` scripts. We had failing tests in schematics that we didn't notice for a couple of months because tests weren't executed on CI.

**Comment by Shijir** [comment]
> Chrome crashes when I try to add a comment to a specific file, so I'm adding the suggestion as a comment instead - it might be good to execute the schematics tests as part of the `yarn test` scripts. We had failing tests in schematics that we didn't notice for a couple of months because tests weren't executed on CI.

HI @sis0k0, yes. I see this volume of file changes in this PR makes it completely impractical to comment on a specific file/line.  So please keep posting your suggestions as comments.

As for the NGC error, we need to use `build:release` specifically which builds `@clr/angular`, `@clr/ui`, and `@clr/icons`. And then if you run `publish` or `publish:local`, you should be able to publish the packages.

For CI build, we need to run `build:ci` which runs all packages as well as apps such as `website`, `dev`, and `adoption.`

**Review by bdryanovski — CHANGES_REQUESTED** [review]
It's hard to write comments on the PR - too many files and Chrome have a hard time so will try to do it in one comment here.

The version of the adoption guide here is pretty old from what we have on the `next` branch. And that is pretty normal to such a big change here. Right now the latest version of the adoption guide is located in `apps/` folder as a standalone app - it has some dependencies of Clarity Core and Angular that I think are not needed and will drop them in the feature to use just the latest released package as a normal app will do.

I'm not sure if the `website` gonna stay on the `next` branch or it will have its own branch? If we keep the `website` on the `next` branch we could totally ignore the adoption project in this branch and drop all changes here for that. 

The adoption guide and website will be at the same branch so we could release both of them at the same time. Right now we don't have a separate domain and it's released inside the website as a subfolder.

NOTE: when I talk about the website I'm referring `clarity.design` (new website)

**Comment by bbogdanov** [comment]
When looking into this branch there are a lot of new(changed) stuff. Could you please clarify what was the intend of this separation outside of just duplicate the `next` branch and remove everything related to `@cds/core`?

**Comment by Shijir** [comment]
@bbogdanov there won't be duplicate angular in `angular` and `next` branches. Once we merge these changes into `angular` branch, we will remove what has been ported over to `angular`. The reasons why we are removing angular from `next` as follows:

- Angular build is currently tied up with Core build. By separating them, we could do releases in an asynchronous way.
- Once we could release `@clr/angular` and `@cds/core` independently from one another, we are considering the option of making `@clr/angular` releases match with `@angular`'s versions which is currently at v12.
- Angular's build process is entangled with Core's build. With this separation, we could remove this entanglement. As such, we could also make build processes in both branches simpler and faster.
- We could also publish our old website with the latest `@clr/angular`. Currently, users can view our old website with `@clr/angular`'s v4 version only.

**Comment by Shijir** [comment]
Closing this PR as the latest changes are going in https://github.com/vmware/clarity/tree/angular-separation-wip

**Pull request closed without merging**
