### PR TITLE
feat(breadcrumb): core breadcrumb component

### PR DESCRIPTION
**Pull request by jeeyun**
Carrying over the external contribution (#5876) so we can do a final fit and finish and merge. 

Co-authored by @derkoe from [Porsche Informatic](https://github.com/porscheinformatik). 🎉 

I will clean up the commit message when we are ready for the final squash/rebase.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mathisscott — APPROVED** [review]

**Review by coryrylan — APPROVED** [review]

**Comment by mathisscott** [comment]
@jeeyun : this looks like we are good to merge. Any chance we could merge it for the next release?

**Comment by jeeyun** [comment]
Yes! I realized forgot to add a react wrapper for this. Let me add that to the PR today and get it reviewed in time for next release?

**Review by mathisscott — APPROVED** [review]

**Review by coryrylan — APPROVED** [review]

**Comment by d-m-s** [comment]
Great to see it finished! 

**Thanks @derkoe, @jeeyun & clarity team for the good collaboration!!!**

**Comment by mathisscott** [comment]
Thanks @d-m-s and @derkoe !

**Pull request merged**
