### PR TITLE
Fix for loader in clr-button   Issue #1681

### PR DESCRIPTION
**Pull request by govi2010**
Signed-off-by: Govinda Alwani <govi2010@gmail.com>

### CODE REVIEW

**Comment by adityarb88** [comment]
@govi2010: This I believe is the one of the right approaches to solve the spinner issue. Could you please add unit tests and then we can review this PR? Please refer to `loading-button.spec.ts` https://github.com/vmware/clarity/blob/master/src/clarity-angular/button/button-loading/loading-button.spec.ts for more details. Also you need to run `npm run clang:format` & `npm run tslint:fix` before submitting a PR to make sure the code is formatted correctly.

Thanks for the contribution!

**Comment by govi2010** [comment]
Ok I will update code by morning

**Comment by govi2010** [comment]
@adityarb88  I have update code. But i don't understand why this is failing. Also i don't know testing framework or how to write it.

**Comment by govi2010** [comment]
@adityarb88 do you need anything on this?

**Comment by youdz** [comment]
Your tests fail because there is a problem with the directives exported by `ClrButtonGroupModule`. One of them appears to be undefined. You should investigate this to fix the unit tests, when it's fixed I think this PR will be good to go.

**Comment by adityarb88** [comment]
@govi2010: Did you get a chance to figure out what @youdz mentioned above?

**Comment by adityarb88** [comment]
Closing this PR because it hasn't been updated and the tests are failing. Duplicate PR which fixes the tests here: #2022

Thanks for the contribution @govi2010

**Comment by govi2010** [comment]
@adityarb88  Sorry, I couldn't get time to work on this. Thanks for completing those test. I really don't know about writing test files.

**Pull request closed without merging**
