### PR TITLE
Fix for bug 2734

### PR DESCRIPTION
**Pull request by AbhiAgarwal192**

### CODE REVIEW

**Comment by AbhiAgarwal192** [comment]
Updated commit message and hence submitting new request.

**Comment by gnomeontherun** [comment]
You can fix your PR by amending your commit to automatically to the signoff using `-s` flag. Also, please revert the package-lock.json file changes.

```
git commit --amend -s
```

**Comment by gnomeontherun** [comment]
I'm actually confused, we already have another PR looking at this #2737

**Comment by cbhumireddy** [comment]
@gnomeontherun : Could you please check and approve [PR](https://github.com/vmware/clarity/pull/2737), waiting for second review to merge. Not sure with whom i can check as i am not able to add reviewers.

**Comment by gnomeontherun** [comment]
I'm going to close this in favor of #2737. Thanks for the PR though, just can't accept both for the same fix!

**Pull request closed without merging**
