### PR TITLE
fix(form): mark only blurred control as touched instead of whole form

### PR DESCRIPTION
**Pull request by Wallabeng**
Signed-off-by: Wallabeng <marcel@ring-mail.at>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Workaround for touching controls (#4767), touches all controls inside a form, because MarkControlService is provided on form level. So validation messages (e.g. for required validator) inside the form are shown, regardless of any user interaction.

## What is the new behavior?
Workaround for touching control touches the blurred control only.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by Wallabeng** [comment]
@bbogdanov, @Jinnie please have a look at this

**Comment by Wallabeng** [comment]
bump! Can anyone have a look at this please? It's blocking us from upgrading to clarity v4.

**Comment by bbogdanov** [comment]
What happens when all controls are touched? Does the form get `ng-touched` in this case?

**Comment by Wallabeng** [comment]
Yes the form and all controls inside it are getting touched. So you also get validation messages for controls the user himself never touched.

**Review by mathisscott — APPROVED** [review]

**Comment by bbogdanov** [comment]
The form gets touched even if only one control is touched. This is what I was looking for cause it is a default @angular/forms behavior. 

LGTM!

**Review by bbogdanov — APPROVED** [review]

**Pull request merged**
