### PR TITLE
[NG] build for Angular 5

### PR DESCRIPTION
**Pull request by dherges**
Current Status: jsdoc annotations, [tsickle emits warnings](https://github.com/angular/tsickle/blob/d24b139b71a3f86bf25d6eecf4d4dcdad3b379e4/src/jsdoc.ts#L171), handled as non-zero exit code by ngc

Solved:
 - [x] dherges/ng-packagr#369

#### BREAKING CHANGES

Due to `@angular/compiler: "^5.0.0"`, AoT metadata will be in `version: 4`. Version 4 Metadata targets Angular 5 and is incompatible with Angular 4!

### CODE REVIEW

**Comment by dherges** [comment]
@hippee-lee FYI

**Comment by hippee-lee** [comment]
@dherges - what makes you think `Source File causing the error: src/clarity-angular/button/button-group/button-group.ts` is the cause? The two properties in there are initialized to empty arrays.
``` inlineButtons: Button[] = [];
    menuButtons: Button[] = [];
```
The error is very general and so far I've been unable to locate its source.

**Comment by dherges** [comment]
I am trying to find a repro but can't. The code isn't really the cause, it's just where it happens...

**Comment by hippee-lee** [comment]
Understood that's what I suspected. Thanks for the follow-up.

**Comment by dherges** [comment]
@hippee-lee WE'Ve advanced error further down!

tsickle reports warning for your jsdoc annotations and thus ngc has [a non-zero exit code](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/perform_compile.ts#L178-L186)

```
src/clarity-angular/button/button-group/button-group.ts(93,5): warning TS0: the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/clarity-angular/button/button-group/button-group.ts(208,5): warning TS0: @type annotations are redundant with TypeScript equivalents
@private annotations are redundant with TypeScript equivalents
src/clarity-angular/button/button-group/button-group.ts(208,5): warning TS0: @type annotations are redundant with TypeScript equivalents
@private annotations are redundant with TypeScript equivalents
src/clarity-angular/data/datagrid/datagrid-hideable-column.ts(11,1): warning TS0: @class annotations are redundant with TypeScript equivalents
src/clarity-angular/data/datagrid/datagrid-hideable-column.ts(20,5): warning TS0: @type annotations are redundant with TypeScript equivalents
src/clarity-angular/data/datagrid/datagrid-hideable-column.ts(30,5): warning TS0: @constructor annotations are redundant with TypeScript equivalents
src/clarity-angular/data/datagrid/datagrid-hideable-column.ts(46,5): warning TS0: @function annotations are redundant with TypeScript equivalents
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
```

**Comment by dherges** [comment]
Here is the [list of jsdoc annotations being reported](https://github.com/angular/tsickle/blob/5987ad32df4d86fd18cd59da47a0f549d716521d/src/jsdoc.ts#L115-L123)

The line numbers in the error messages may be wrong because of the resource inlining / source rewrite by ng-packagr.

**Comment by hippee-lee** [comment]
@dherges - thanks for the hint on jsdoc annotations. 
I was able to make a small mod and see the errors when building. 

We are also going to bump `ng-packagr` and `angular` versions in the rename PR. Thanks for both `ng-packagr` project and the input here! I really appreciate it.

I'll leave this open until those go in.

**Comment by hippee-lee** [comment]
@dherges - I made these changes in our rename pull request that upgraded the `ng-packagr` version so I'm closing this pull request as it also relates to issue #850. 

Thanks again for the wonderful `ng-packagr` project!

**Pull request closed without merging**
