### PR TITLE
[Web] Minor typo in datagrid demo

### PR DESCRIPTION
**Pull request by amellnik**
Signed-off-by: Alex Mellnik <a.r.mellnik@gmail.com>

### CODE REVIEW

**Comment by youdz** [comment]
@adityarb88: If we're not using it anymore, should we delete the branch? Or at least document in big bold letters that it's not used anymore?

**Comment by adityarb88** [comment]
@youdz: Yes. I think it was kept for backup just in case we had to revert back to the old website. But we will rename it to make sure that no one contributes to it. Will also update the contribution docs for the website.

**Comment by adityarb88** [comment]
cc: @gnomeontherun

**Comment by hippee-lee** [comment]
I meant to ask on the dev channel last week about deleting the old branch and handle it as part of the release. I got sidetracked with the release issues that came up. I'm all for removing the old/unused branch.

**Comment by gnomeontherun** [comment]
I don't think we need the old branch either, but this issue does exist in `website` as well so either we fix this on the next release or @amellnik can submit a different PR to the `website` branch and make the change there.

**Comment by amellnik** [comment]
I'll submit a corrected PR that also mentions the change in Contributing.md this evening.

**Comment by gnomeontherun** [comment]
Awesome, thanks!

**Comment by amellnik** [comment]
Superseded by https://github.com/vmware/clarity/pull/2042 and https://github.com/vmware/clarity/pull/2043.

**Pull request closed without merging**
