### PR TITLE
[WEB] new documentation format for wizard

### PR DESCRIPTION
**Pull request by mathisscott**
screen shot 2017-05-18 at 5 46 17 pm
screen shot 2017-05-18 at 5 46 29 pm
screen shot 2017-05-18 at 5 46 37 pm
screen shot 2017-05-18 at 5 46 43 pm
screen shot 2017-05-18 at 5 46 51 pm
screen shot 2017-05-18 at 5 47 09 pm

Signed-off-by: Scott Mathis <smathis@vmware.com>

### CODE REVIEW

**Comment by reddolan** [comment]
@mathisscott Sizes section: M, L, XL boxes are green but should be purple like on the [Modals](https://vmware.github.io/clarity/documentation/modals) page. That is unless you thought it needed to be different for some reason.

**Comment by mathisscott** [comment]
@reddolan 
That was intentional. I went with a different color so that users would be less likely to confuse Wizards and Modals. I can make it a different color if you would prefer.

**Comment by reddolan** [comment]
@mathisscott I don't remember seeing that green used elsewhere on the site. I think keeping it purple is fine. I am not sure if changing the color is going to help that much. And for consistency, we seem to be using that purple for callouts on the site

**Comment by mathisscott** [comment]
@reddolan 
Cool. I'll change it back to purple before merging it in. Thanks!

**Pull request merged**
