### PR TITLE
fix(datagrid): trackBy items by provided trackBy option

### PR DESCRIPTION
**Pull request by bbogdanov**
When we have two for loops in a single `<clr-datagrid>` but one of them has a `trackBy` in simple `ngFor` and another one is inside `*clrDgItems` `ClrDatagridItemsTrackBy` selector only selects the `trackBy` of the simple `ngFor` because this is what we told Angular to search for and Angular never went searching for `clrDgItemsTrackBy` directive which represents the `trackBy` in `clrDgItems`. 

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3936

## What is the new behavior?

The correct trackBy function is applied when using `*clrDgItems` 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Jinnie** [comment]
It would be nice to have some tests with the specific reported setup, with two loops with trackby, and make sure there is no interference both ways.

**Comment by bdryanovski** [comment]
I also think that some tests could be helpful here ..

**Comment by gnomeontherun** [comment]
I'm not sure this won't break the ngFor support for trackby. Please make sure we have a way to test both clrDgItems and ngFor use cases and that we pick up the right trackBy.

**Review by Jinnie — APPROVED** [review]
LGTM

**Review by bdryanovski — APPROVED** [review]

**Comment by gnomeontherun** [comment]
Also we should first make this PR against `master` and then work on backports.

**Comment by bbogdanov** [comment]
The issue and its example were quite misleading so it took me more time to figure out what's happening.

The `ClrDatagridItemsTrackBy` actually never goes to `clrDgItems` to take the provided `trackBy`. It will get only `ngFor` and the last declared `trackBy` will be assigned to `Items`. it works Many(Direcvites) -> One(grid items) and the last one wins.

`Items` directive needs to get the `trackBy` function in order the [Selection<T>](https://github.com/vmware/clarity/blob/881d93b39dd530f9d4afa1fea76d4a99f59f4296/packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts) directive to use it to track/select the correct items.

I think this is the only thing we need to fix here from our side related to `trackBy` in `Datagrid`. Anything else that provides `trackBy` inside the datagrid I think is a sign of poor implementation and needs a redesign.

Another solution that comes into my mind rn will be to remove the `ClrDatagridItemsTrackBy` directive and provide an `@Input` in `ClrDatagrid` component with `trackBy` function for the items. That way we will get rid of Many -> One relation and let the users use as many `ngFor` and `trackBy` as they want in the datagrid.

**Comment by gnomeontherun** [comment]
This looks like a better solution here, but adding @hippee-lee as a reviewer to double check this since he made the change to the iterable proxy setup (granted this was a while ago). 

We used to do this, but it was refactored and seems to mean we don't capture trackby properly. I think this fix is good, but wanted to check on side effects. https://github.com/vmware/clarity/blame/f6a4874497655fbf6859f8a1417dc92d1e48f984/src/clr-angular/data/datagrid/datagrid-items.ts#L51

**Review by hippee-lee — APPROVED** [review]
It has been a while. I think this is better than adding a new input to the datagrid. I recall that the tests for mutating the array were a warning indicator  that something wasn't working correctly with the trackby fn provided. From waht I recall, as long as those tests are still passing this is the best fix for the issue linked to this PR.

**Comment by Shijir** [comment]
@bbogdanov after some investigation, I don't think this PR is solving #3936.

The trackyBy function on columns is being mistaken for the row items' trackby. So the culprit is in the assignment we make in `datagrid-items.tracky.ts` where we first instantiate and overload Angular’s default `[ngForTrackBy]`. That means any `trackyBy` function whether it’s on row items or some other datagrid component element will be used for row items `trackBy`. So we have to do that assignment of `this._items.trackBy = value` only after we make sure that the `trackyBy` is being used on row items. But that’s really hard… I just don’t see any way to check and make sure ngForTrackBy is being used on rows at this moment. 

The workaround to the issue is not to use `ngForTrackBy` anywhere except on row items AFAIS. Here, our first mistake was to overload a default Angular directive and assumed it would be used only on row items. As Matt suggested above, we could add another `@input` in `clr-dg-row` for its `trackBy` function.

**Comment by bbogdanov** [comment]
@Shijir Actually this will solve the issue because `clrDgItems` will apply the `trackBy` because it is the last instance. Anyway I am not actually trying to solve the entire situation with `ngForTrackBy` directive, because there is no point in doing that and it is something we would like to avoid supporting. What we will do is to encourage everyone to avoid using trackBy on anything else than `clr-dg-row` or in `clrDgItems` because there is no benefit at all to have a `trackBy` on anything else in the datagrid. 

P.S. Matt is saying actually the opposite of what you thought he is saying.

**Review by Shijir — COMMENTED** [review]
@bbogdanov yes, that will be the case only if a user is using `clrDgItems`, and the `ngForTrackBy` on rows happens to be the last one in Datagrid. But as I said, the culprit is in overloading the default Angular directive and not fixed by this PR. Without fixing the culprit, we are only addressing that specific user's case. You can see that other cases where ngFor and ngForTrackBy are being used on actionable buttons. Or if these directives are used in row detail or detail pane, etc., we will still see similar issues.

Sorry, I misread what Matt wrote. But the point is that we don't have to overload `[ngForTrackBy]` to accept the trackBy function; it could be simply through `trackBy` input on `clr-dg-row`.

**Comment by bbogdanov** [comment]
@Shijir From your last comment, I understand that you would like to remove the `ClrDatagridItemsTrackBy ` directive. I would like to do that too but it is a breaking change. I suggest we at least give the users a major release period of time to change their approaches from using `ngFor` to `clrDgItems` and then remove the directive. 

About the input on `clr-dg-row` I think it getting back to the same approach we have with the directive. We will face the same issue. The last `clr-dg-row` with a `trackBy` will win. (If I understand you correctly)

**Comment by Jinnie** [comment]
Not overloading the directive is the right solution for the long term, but this will require us to discard the use of ngFor, which will be a big breaking change. It will be great solution, too, as using clrDgItems vs ngFor is a common source of confusion. Nevertheless, we have this as tech debt and I don't think it's the right time for this at this point of the product lifecycle. I hope we won't have the same problem in Core.
Also, having trackby in ngFor used for columns is useless - how many items do you have there, why would you want to update them dynamically and preserve state, what state? Hhaving it in action buttons - the same.
In internal ngFors is also a sign of bad architecture and design, though we may see it occasionally. It would be great to be able to avoid it on the Clarity side, but I don't think it's critical and worth the heavy lifting effort at this moment.
In the same time, having clrDgItems silently drop the trackby is a trap that got several devs into and required extensive research and debugging. It's an outstanding problem and its fix is not breaking change.

So, my suggestion is to split the overload scenario from the current case and file new issue for the overload, so we can plan it for some major update. I confirm my approval review for the currently presented commit.

**Comment by Shijir** [comment]
> Not overloading the directive is the right solution for the long term, but this will require us to discard the use of ngFor

I think we should try to remove the overloaded instance of `ngForTrackBy` in one of the next major releases. But I don't quite understand how that will force us to discard the use of `ngFor`.

> Also, having trackby in ngFor used for columns is useless

Yes, I agree! Because of that, I thought, we should just recommend not to use `ngForTrackyBy` on anywhere except exactly 
 on rows until we solve the root cause of the issue once and for all.

> my suggestion is to split the overload scenario from the current case and file new issue (or discussion) for the overload, so we can plan it for some major update

The dilemma I am facing here is that this PR solves just one symptom of the issue. But at the same time as we haven't addressed the root cause, we will see other reports of similar or related symptoms. Actually, in the comment section of the issue, we've already received them.

I agree that it's probably better to separate the overload issue from the case scenario this PR is solving. So I will just remove my block on this PR. But we also need to file another issue to track for the overloaded `ngForTrackBy`.

**Review by Shijir — APPROVED** [review]

**Comment by bbogdanov** [comment]
#5044

**Review by gnomeontherun — APPROVED** [review]
Thanks all, glad we got a consensus.

**Pull request merged**
