### PR TITLE
[WEB] icon detail snippet fix

### PR DESCRIPTION
**Pull request by Shijir**
- added in more tags for searching as well

Preview: https://shijir.github.io/clarity/icons/icon-sets

Signed-off-by: stsogoo <stsogoo@vmware.com>

### CODE REVIEW

**Comment by jeeyun** [comment]
With all the format changes, it's a bit hard to identify what's fixing the issue at hand. Can you briefly explain or just highlight the relevant code changes for me?

**Comment by Shijir** [comment]
@jeeyun our `clr-code-snippet` component wasn't working as it should. When the value of its `[clrCode]` changes, it wasn't updating the view. I think the problem lies in how we used `prism.js` in the `clr-code-snippet` component. That's why I didn't use the component and resorted to using raw code snippets.

**Comment by adityarb88** [comment]
@shijir refer to this issue: https://github.com/vmware/clarity/issues/98

**Comment by adityarb88** [comment]
@shijir is this PR going to be merged in 0.10.5? If yes we should update the milestone so that @gnomeontherun knows to merge this after the publish.

**Pull request merged**
