### PR TITLE
Fix: A modal window takes place when it is in a hidden state #1622 #1648

### PR DESCRIPTION
**Pull request by govi2010**
Fix: A modal window takes place when it is in a hidden state #1622 #1648
Signed-off-by: Govinda Alwani <govi2010@gmail.com>

### CODE REVIEW

**Comment by govi2010** [comment]
@adityarb88  end up by delete my all commits and just change those line.

**Comment by govi2010** [comment]
@adityarb88  You labeled DO-NOT-MERGE. Do you need anything from my end ?

**Comment by govi2010** [comment]
@adityarb88  You labeled DO-NOT-MERGE. Do you need anything from my end ?

**Comment by adityarb88** [comment]
@govi2010: No. This PR is also set to be merged into master next week. We have already finalized whats going in for tomorrow's release, so I don't want to add a last minute change. Thats why the `DO-NOT-MERGE` label.

**Comment by adityarb88** [comment]
@govi2010: No. This PR is also set to be merged into master next week. We have already finalized whats going in for tomorrow's release, so I don't want to add a last minute change. Thats why the `DO-NOT-MERGE` label.

**Comment by adityarb88** [comment]
@govi2010: No. This PR is also set to be merged into master next week. We have already finalized whats going in for tomorrow's release, so I don't want to add a last minute change. Thats why the `DO-NOT-MERGE` label.

**Comment by govi2010** [comment]
Ah... OK . I will look for next bug.

**Pull request merged**
