### PR TITLE
Fix for #655

### PR DESCRIPTION
**Pull request by spadidapelli**
Hi,

I have added the changes requested in latest visual spec #655.
Please review.

Thanks,
Srinivas
Signed-off-by: srinivas padidapelli <spadidapelli@gmail.com>

### CODE REVIEW

**Comment by youdz** [comment]
@spadidapelli: Can you merge all your changes into a single commit whose message ends with `Signed-off-by: srinivas padidapelli <spadidapelli@gmail.com>`?

That'll take care of the `dco-required` tag and will allow us to merge a single cleaner commit. Thanks! 😄

**Comment by spadidapelli** [comment]
Hi @youdz,

I have squashed all the commits in to one and added Signed-off message for each commit. Please let me know if anything else is required. 

Thanks for your support.

**Comment by adityarb88** [comment]
@lil-kim: Here is the diff report for this change: https://s3.amazonaws.com/travis-ci-jeeyun/adityarb88/clarity/368/368.2/home/travis/build/adityarb88/clarity/gemini-report/index.html

Please review.

**Comment by adityarb88** [comment]
Hi @spadidapelli: It looks like the squash didn't work. We still see 5 commits:

image

**Comment by spadidapelli** [comment]
HI @adityarb88,
I have squashed all the commits in to one in 6b70d10. please let me know if anything else is required.

Thanks,
Srinivas P

**Comment by adityarb88** [comment]
@spadidapelli: It doesn't look like that. If you look at the `Commits` section on your PR, you will see 5 commits. Might be a rebase issue with master?

**Comment by spadidapelli** [comment]
Hi @adityarb88 and @lil-kim,
squash and icon size request fixed in pull request #762. can you please review?
Regards,
Srinivas P

**Comment by SrinivasPadidapelli** [comment]
Hi @adityarb88 and @lil-kim,
squash and icon size request fixed in pull request #763. can you please review?
Regards,
Srinivas P

**Comment by adityarb88** [comment]
Closing this because you already create a different PR

**Pull request closed without merging**
