### PR TITLE
[NG] Fix text blurriness when hovering clickable card

### PR DESCRIPTION
**Pull request by jansivans**
blurriness
On the left side you can see current behavior when hovering clickable card - text becomes a little bit blurry.
On the right side you can see fixed version.

### CODE REVIEW

**Comment by adityarb88** [comment]
@jansivans: Which browser do you see the blurred text in? I can't replicate this on Chrome.

**Comment by jansivans** [comment]
@adityarb88 I am using Chrome as well.

**Comment by adityarb88** [comment]
@jansivans: I can't replicate this issue. Are you using Windows? I don't mind approving this PR as it just translates on the Y axis and it doesn't touch the other axes. But before doing that would you mind squash your commits to just one and adding a dco? If this is too much trouble for a one line PR, I can do the change myself if you can confirm your OS as I cannot replicate this on my mac. Thanks for the contribution!

**Comment by jansivans** [comment]
@adityarb88 yes I am using Windows and my colleague who also has this issue uses Windows as well. I don't mind if you change it by yourself because I didn't sign off my commit at first and was having troubles on signing it off later.

**Comment by adityarb88** [comment]
@jansivans: Sure. I will get this fix in. Thanks for the raising the issue!

**Comment by adityarb88** [comment]
Fix merged into master. Will be released next week. Closing this PR. Thanks!

**Pull request closed without merging**
