### PR TITLE
fix: fixing static errors inside datagrid-pagination

### PR DESCRIPTION
**Pull request by bdryanovski**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by Jinnie — APPROVED** [review]

**Review by coryrylan — APPROVED** [review]

**Comment by hristozov** [comment]
This is a breaking API change forcing all consumers using stuff like `pagination.totalItems` to explicitly deal with converting `string | number` back to `number`, e.g. with a custom pipe (couldn't find a clean way to do casts in templates in a type-safe manner). Also, if we want to get philosophical, the meaning of what `string` means is unclear (e.g. "Is it base-10?", "How can I parse it?", etc.). FWIW, I hit this while migrating from Clarity 4 to Clarity 5.

Please, when you revisit that code in the future, consider switching back to supplying just a `number` and doing the `string` -> `number` conversion in `datagrid-pagination.ts`.

**Comment by bbogdanov** [comment]
@bdryanovski `fix(angular:grid):` Just reminding because soon messages without a project and scope will require manual edit for the changelog

**Comment by bdryanovski** [comment]
This is merged 5 months ago .. don't get the point here 

@bbogdanov

**Comment by bbogdanov** [comment]
@bdryanovski  Ah sorry! I received an update but I missed the fact it was merged long before the commitlint changes. My bad!

**Pull request merged**
