### PR TITLE
chore(dropdown): remove dead code

### PR DESCRIPTION
**Pull request by wesleycho**
- Remove unused code

Signed-off-by: Wesley Cho <wesley.cho@gmail.com>

### CODE REVIEW

**Comment by adityarb88** [comment]
Hi @wesleycho. Thanks for checking out Clarity. We really appreciate your suggestions/feedback. 

I tried removing the highlighted code in your PR locally but when I click on the `.dropdown-toggle`, the menu opens but its immediately closed because this logic, which was removed, detects if the click was inside or outside of the dropdown component. We want to close the menu when the click is outside of the dropdown component but also ignore click events which were inside of the dropdown component.

What this helped me realize is that there is a unit test in dropdown which is a false positive. I ll try to get that fixed ASAP. 

Thanks again!

**Comment by wesleycho** [comment]
Ah shoot, I missed that there is a `return` - how come it isn't just checking for
```ts
if (dropdownHost.contains(target) {
```
?

**Comment by adityarb88** [comment]
We tried that too but for I believe that `.contains` (please correct me if I am wrong here) only detects clicks on immediate children. If for example a `.dropdown-item` is clicked, the `.contains` method won't be able to detect it. Thats why we went with the while loop.

**Comment by wesleycho** [comment]
I just selected an element in Chrome and did `$0.contains($0)`, it returned `true`.

**Comment by adityarb88** [comment]
@wesleycho: I tested it again. It doesn't work. Try doing this:

```
if (dropdownHost.contains(current)) {
      console.log("Inside Host");
}
```

in the `onMouseClick` event handler and you wont get the console log when you click on the `.dropdown-item` but you will see the log when you click on the toggle or the menu

**Comment by wesleycho** [comment]
Weird - going to close this PR since it looks like I erroneously deleted code and it seems like there's nothing worthwhile changing here atm.

I'll probably file some PRs cleaning up some other stuff I noticed at some point later this week when I fix my own ng2 issue at work :) .

**Comment by adityarb88** [comment]
Thanks!

**Pull request closed without merging**
