### PR TITLE
[ICONS] created new categories for icons

### LINKED ISSUE #1159: Create "commerce" category for Clarity Icons
Currently, we have a number of "commerce/finance" icons packed into the Essentials category. This bloats essentials with icons that many non-ecommerce webapps may not use. Note the non-trademarked icons in #501 would go in this category as well.

We'll need @lil-kim to answer two questions:

1. Do we need a separate category for commerce/finance/marketplace icons? Why not if the answer is "no"?
2. What should we call the new category?
3. Which icons do we need to relocate there? (Please update the confluence doc to reflect this migration. Whoever implements this change should use the confluence doc as a guide.)

Then we'll need @Shijir or whomever is assigned to implement this to perform the migration from Essentials to the new category.

This constitutes a breaking change so it should go into a minor release. If possible, I would prefer it go into 0.10. If not, it will have to go into 0.11 and should be completed before Clarity Icons is finalized.

### PR DESCRIPTION
**Pull request by Shijir**
Closes #1159, #1160, #1161

- Are there any icons you would suggest to move to another set?
- Do we still want to keep duplicates of icons across different sets? As we are moving icons into smaller and more specialized sets, I think we shouldn't have the same icons in different sets. 

clarityiconsnewcategories

Signed-off-by: Shijir Tsogoo <stsogoo@vmware.com>

### CODE REVIEW

**Comment by mathisscott** [comment]
At a glance, the `repeat` icon should probably be in Essentials, not Media. That type of icon gets used for all sorts of things in web apps.

CC @lil-kim

**Comment by mathisscott** [comment]
I think duplicating among sets is something we should avoid.

**Comment by Shijir** [comment]
Fyi, here is the published svg files. [all-shapes.zip](https://github.com/vmware/clarity/files/1174521/all-shapes.zip)

**Comment by Shijir** [comment]
clarity

**Pull request merged**
