### PR TITLE
Update error object in clrIfError context

### PR DESCRIPTION
**Pull request by gerinjacob**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Once the view is rendered, error object not getting updated in the context. This leads to error object to be out of sync.

Issue Number: N/A

## What is the new behavior?

If the view is already rendered, update the context with new error object.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bbogdanov — CHANGES_REQUESTED** [review]
Commit message `fix(angular:form):`

**Comment by gerinjacob** [comment]
> Commit message `fix(angular:form):`

There was a commitlint that was preventing me from selecting `angular:form` as topic.

Was getting the error,
`✖   scope must be one of [angular, a11y, accordion, alert, badge, build, button, card, checkbox, color, combobox, datagrid, datalist, date-picker, dropdown, form, form-group, grid, header, i18n, input, label, list, login, modal, navigation, pagination, password, progress-bar, radio, schematics, select, sidenav, signpost, spinner, stack-view, stepper, table, tabs, textarea, timeline, toggle, tooltip, tree-view, vertical-nav, wizard, icons, range, website, panel] `

So the choice was between `angular` or `form`, since `angular` topic is too generic, decided to go with `form`

**Comment by bbogdanov** [comment]
> > Commit message `fix(angular:form):`
> 
> There was a commitlint that was preventing me from selecting `angular:form` as topic.
> 
> Was getting the error,
> `✖ scope must be one of [angular, a11y, accordion, alert, badge, build, button, card, checkbox, color, combobox, datagrid, datalist, date-picker, dropdown, form, form-group, grid, header, i18n, input, label, list, login, modal, navigation, pagination, password, progress-bar, radio, schematics, select, sidenav, signpost, spinner, stack-view, stepper, table, tabs, textarea, timeline, toggle, tooltip, tree-view, vertical-nav, wizard, icons, range, website, panel] `
> 
> So the choice was between `angular` or `form`, since `angular` topic is too generic, decided to go with `form`

https://github.com/vmware/clarity/blob/c13d9dc17d3c6c95f99c311685f832564fb11ebe/commitlint.config.js#L2 add here a new line with `'angular:form',`

**Review by bbogdanov — APPROVED** [review]

**Review by mathisscott — APPROVED** [review]

**Comment by bbogdanov** [comment]
Thank you @gerinjacob for the contribution!

**Comment by rbirkgit** [comment]
I would love to have this for v5.

**Comment by gerinjacob** [comment]
> I would love to have this for v5.

https://github.com/vmware/clarity/pull/6209

**Pull request merged**
