### PR TITLE
chore: provide a way to visualy test components

### PR DESCRIPTION
**Pull request by bdryanovski**
Provide a way to compare component pages for changes after refactoring or bug-fixes. By creating a base snapshot of before and compare it after the code change. Looking for color changes or misalignment.

```bash
$ cd tools/visual-tester
$ node index.js
```
If everything is successful the output of the command will be something similar to that. 

Screenshot 2020-10-06 at 12 05 49

For example, if we made check somewhere
Screenshot 2020-10-06 at 12 51 05

And re-run the task we have to get at least one failing test for example
Screenshot 2020-10-06 at 12 41 45

There are two additional images that will be created called `current` and `diff`

  * `current` - this is the current snapshot made the last time the task was run - reflecting the current state of the app.
  * `diff` - this is an image that will show by highlighting the changed part of the snapshot

Current
buttons-primary-button-current

Diff
buttons-primary-button-diff

```ts
// Basic test
it('url/path/to/page', options)

// Test that will be ignored
xit('url/path/to/page', options)

// Test that will be focused - if the runner pick one `fit` test it will 
// run only `fit` marked tests
fit('url/path/to/page', options)
```

The options pattern are letting you change how the `diff` image will be generated or for example to disabled `animations` bypassing

```ts
it('datagrid/server-driven', {ignoreCSSAnimations: true});
```

## Addition

There is a second reporter that will just add more information on the runtime named `console` to trigger it just add `--reporter=console`

## TODO 
  * Check performance
  * Make tests run against other specs with a different setup.
  * Update documentation
  * Let the test run against DOM Selector to limit arias like menus, headers, and others.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hippee-lee** [comment]
This looks good to me. Simple and straightforward. It looks flexible enough that we can modify it as we make use of it. E.g - using the website storybook apps as a test site or grouping tests better with files or adding a describe.

Before I approve, I want to discuss the reference images. I thought we wanted to get away from storing the reference images in our repo?

**Comment by gnomeontherun** [comment]
We should drop the reference images from the repo for now. Before we can make this part of CI/CD, we'd have to work out how to manage the updates. Until then, we can run things manually.

**Review by gnomeontherun — COMMENTED** [review]
I'm ok with what we have here for now, with the exception of the reference images. For the time being, we can setup a second repository to store those and not complicate our repo unless it turns out we really want to.

**Review by hippee-lee — DISMISSED** [review]

**Comment by bdryanovski** [comment]
Will update my PR and drop the images and add them as part of the `.gitignore` to be sure that they won't mess the `git status` and accidentally  be added back to `tracked files`

**Review by gnomeontherun — APPROVED** [review]

**Review by hippee-lee — APPROVED** [review]

**Pull request merged**
