### PR TITLE
feat(form): add error object to clrIfError context

### PR DESCRIPTION
**Pull request by gerinjacob**
Close: #4345

Signed-off-by: Gerin Jacob <gerinjacob@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [x] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #4345

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by gerinjacob** [comment]
> Thanks @gerinjacob this looks good.
> 
> The only thing is can we add a small snippet on the documentation showing this in the forms page? Also can you update your commit message to:
> 
> `feat(form): add error object to clrIfError context`

Done

**Comment by gnomeontherun** [comment]
We'd like to backport this one to v2, should be pretty clean.

**Comment by gnomeontherun** [comment]
@mathisscott can be merged for this week's release

**Comment by gerinjacob** [comment]
@mathisscott, this will be back ported to 2.x as well right?

**Comment by rbirkgit** [comment]
I would love to have this for v5.

**Pull request merged**
