### PR TITLE
docs(progress-bar): update docs and deprecate for removal

### PR DESCRIPTION
**Pull request by hippee-lee**
Signed-off-by: Matt Hippely <mhippely@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] If applicable, have a visual design approval

@colinreedmiller - I'll add a link in the comments when the preview is built. 

## PR Type

What kind of change does this PR introduce?
Deprecates parts of the ClrProgressBar api.
Adds a new style for user defined style (color)
Updates the documentation recommendations and examples for both colors and variations. 

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [x] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [x] Other... Please describe:
This also adds a scss variable and class for a user defined progress color `$clr-progress-user-color`. 

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by hippee-lee** [comment]
@colinreedmiller - here is the links to the preview: https://deploy-preview-3831--vmware-clarity.netlify.com/documentation/progress

**Comment by hippee-lee** [comment]
@clane and @colinreedmiller - please take a look at the updated docs page for progress bar. It includes the changes requested by Colin and a re-organized layout that uses the newer layout to structure the content. 

https://deploy-preview-3831--vmware-clarity.netlify.com/documentation/progress

Please take a look at the following sections

- Accessibility
- Color
- Variations

**Comment by clane** [comment]
Looks good but I think there is a typo at "An option percentage label ". I should say "optional".

**Comment by gnomeontherun** [comment]
This doesn't appear to be a backport, it should only go into `master` since we'll be deprecating it as of 3

**Comment by clane** [comment]
Regarding the statement "An optional percentage label can be included after the progress bar as needed" we should also mention that this additional percentage label has to be programmatically associated with the progress bar it is representing. This can be done by passing multiple id property references to aria-labelledby. Additionally, our example that demonstrates having two labels for a progress bar should actually have two visual/programmatic labels as it currently does not.  I recommend to follow the example below.

```

<div id="asset1loadingProgressLabel1">Container 1 loading Progress </div>
<progress aria-labelledby="containerloadingProgressLabel1 containerloadingProgressLabel2"  max="100" value="65" data-displayval="65%"></progress><!---->
<span  id="containerLoadingProgressLabel2" aria-live="polite">65%</span>

```

**Comment by clane** [comment]
Just realized that the screen reader user may hear "65%" before they actually read progress bar and its labels due to the live region. Since the screen reader user may hear "65%" out of context, can we make this  message more complete?

<span  id="containerLoadingProgressLabel2" aria-live="polite"><span class="clr-sr-only">Container 1 Loading Progress is</span>65%</span>

**Pull request merged**
