### PR TITLE
[UI] Fixes select/multiselect option colors

### LINKED ISSUE #1853: [UI] Dark theme select options are not visible
### Edit
Stackblitz with v2 reproduction: https://stackblitz.com/edit/gh-1853-select-input-dark-theme-issue

**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Select option text should be readable

### Actual behavior
Select option text is not visible

### Reproduction of behavior
edge_select-bug
firefox-select-bug
ie_11_select-bug

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**

* **OS and version:** Windows 10

* **Browser:** [ Chrome XX, IE11, Firefox ]

### PR DESCRIPTION
**Pull request by hippee-lee**
### Notes
- Updates light theme colors (instead of relying on browser default for multiselect) per discussion w/ @lil-kim 
- Adds new css reference images for light theme
- Screenshots of open selects are difficult to capture on windows, some of them below were captured while it was closing (after the screenshot click)
- Tested in: IE11, Edge and Firefox (on macOS and Windows 10) 
- Fixes #1853

### Before
- IE11 screen shot 2018-02-01 at 4 59 07 pm
- Edge screen shot 2018-02-01 at 4 56 22 pm
- Firefox screen shot 2018-02-01 at 4 55 06 pm

### After
- IE11 ie11
- Edge edge
- Firefox screen shot 2018-02-01 at 4 46 36 pm
Signed-off-by: Matt Hippely <mhippely@vmware.com>

Signed-off-by: Matt Hippely <mhippely@vmware.com>

### CODE REVIEW

**Comment by adityarb88** [comment]
Quick question: Why didn't we test this on Chrome and Safari?

**Comment by adityarb88** [comment]
Also have you verified the multi select colors? I don't see any demo/examples of that in the screenshots you pasted.

**Comment by hippee-lee** [comment]
The default behavior for selects/multi-selects in Chrome and Safari worked, the bug was filed for Firefox I think but it was also broken in IE/Edge. 

btw I did test it, just didn't take screenshots but I can take some and post them if you think its needed.

**Comment by adityarb88** [comment]
No as long as you tested, I am fine. Just wanted to check once because I didn't see that in the PR description.

**Pull request merged**
