### PR TITLE
[WEB] Fix wrong example for from validation

### PR DESCRIPTION
**Pull request by mcosta74**
Fix the example for multiple validators

Closes: #2538

Signed-off-by: Massimo Costa <costa.massimo@gmail.com>

### CODE REVIEW

**Comment by gnomeontherun** [comment]
See https://stackoverflow.com/questions/51775377/clarity-clrformsnextmodule-clriferror-reactive-forms/51813815#51813815

**Comment by mcosta74** [comment]
@gnomeontherun, I created the issue and the PR starting from this SO question

**Comment by gnomeontherun** [comment]
Yes, thank you! Just wanted others to be able to see it if they didn't already.

**Comment by mcosta74** [comment]
Small question about documentation PRs. how often you rebuild the online documentation? how long this fix fix will take to go online??

**Comment by gnomeontherun** [comment]
It usually takes 15-30 minutes for it to be generated automatically by our Travis CI build, depending on how busy it is.

**Comment by mcosta74** [comment]
cool I see now my changes online

**Pull request merged**
