### PR TITLE
[ICONS] Adding new icons

### LINKED ISSUE #500: New set of Icons (vol 4) to be Published
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Description
The purpose of this ticket is to track icon deliveries and implementation (post to the site; add to codebase). A new set of icons will be attached to this ticket once a week by Lilia. Every 2weeks, the 2 sets are to be released to the Clarity site.

### PR DESCRIPTION
**Pull request by Shijir**
Signed-off-by: Shijir Tsogoo <stsogoo@vmware.com>

Resolves #500, #498, and #508.

### CODE REVIEW

**Comment by Shijir** [comment]
clarity

**Comment by Jinnie** [comment]
Great work!
I was looking for both ellipsis and angle-doubles yesterday and had to consider substitutes.
Btw, can't ellipsis be manipulated with direction keywords/attribs? Or the base is different and vertical is centered?

**Comment by Shijir** [comment]
Hi @Jinnie, You can manipulate ellipsis-horizontal and ellipsis-vertical shapes through `dir` attribute just like any other shapes. We could have chosen the route of offering only of them and let users rotate the icon to their choice of direction. The problem with that approach is that the icon has a "badged" state. So when the icon is rotated, users will face cases that badges don't appear in the appropriate position, which is the upper-right side.

As you can see, I added `dir="left"` attribute to the `ellipsis-vertical` shape and its badge's position looks off compared to other icons in `badged` state.

screenshot 2017-02-22 10 39 08

**Comment by Jinnie** [comment]
Thanks for the explanation. This probably applies to all icons. I'll keep it in mind

**Pull request merged**
