### PR TITLE
fix(dropdownmenu): keyboard accessibility issue when there is a div t…

### PR DESCRIPTION
**Pull request by SaiSatwik**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Keyboard navigation with down arrow button is not working on clarity dropdown options when there is a wrapper div around dropdown items inside clarity dropdown menu. This issue is because @ContentChildren is not detecting the content with div tag in between with Angular9 and above.

Issue Number: N/A

## What is the new behavior?

Adding { descendants: true } on Content Children to get the nested items. With this change keyboard accessibility is working and focus is moving to first dropdown option on triggering dropdown menu even in the presence of nested div around dropdown items. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bdryanovski — APPROVED** [review]

**Review by Jinnie — CHANGES_REQUESTED** [review]
Thanks for the contribution, first!
Using `{descendants: true}` seems to be the correct way to fix this behavior at first, but I have some memories that we've tried it and it may be leading to serious issues with the nested menus. Can you please verify the scenario?

**Comment by jeeyun** [comment]
> Using `{descendants: true}` seems to be the correct way to fix this behavior at first, but I have some memories that we've tried it and it may be leading to serious issues with the nested menus. Can you please verify the scenario?

I just tested real quick and this solution does not work for the reason @Jinnie mentioned. When we have nested menu with submenus that are eagerly loaded (e.g. without using `clrIfOpen`), using `{descendants: true}` has effect of including all the descendents in the keyboard navigation when using up/down arrow.

**Comment by SaiSatwik** [comment]
Hi @Jinnie/ @jeeyun, then is there any workaround for this. We have div tag inside clr-drodown-menu  in vmware nsx-t codebase. We have used it for some styling purpose for the dropdown. This used to work for us with clarity version 2.4.0 and angular 8.2.2. Keyboard accessibility broken when we upgraded to clarity version 4.0.3. This is an serious issue for us as we have used div tags at many places inside clr-dropdown-menu.

**Comment by jeeyun** [comment]
Hi @SaiSatwik,
I would suggest getting rid of the wrapper div and modify your css customization in the application side. 

Here's a modified fork of your initial example to apply customization without using the wrapper div: https://stackblitz.com/edit/clarity-light-theme-playground-n2fixc?file=src%2Fapp%2Fapp.component.html

**Comment by hippee-lee** [comment]
Closing this for now due to the work around.

**Pull request closed without merging**
