### PR TITLE
[Typo][Documentation] fixed occurences of the word pokémon

### PR DESCRIPTION
**Pull request by pastparty**
Signed-off-by: Christoph Sippel christoph.sippel@glossybox.com

## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

Fixes a typo.

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [x] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?
Wrong wording.

## What is the new behavior?
Right wording :)

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Other information

There was a mix-up of the grave accent `` ` ``and the acute accent `´`
Source: https://en.wikipedia.org/wiki/Pokémon

### CODE REVIEW

**Comment by amellnik** [comment]
This bug might have been introduced by me -- good catch!

**Comment by gnomeontherun** [comment]
@pastparty can you update your PR with a signoff on the commit to merge?

**Comment by gnomeontherun** [comment]
@pastparty Before we can merge you'll have to do a signed-off-by annotation on your commit, or we'll have to reimplement it ourselves in a different PR to close this out. Can you update your commit with sign off?

**Comment by hippee-lee** [comment]
@pastaparty, are you able to sign this commit and push that to the branch? If you need help signing a commit take a look here or let me know if I can help walk you through the commands. 

More info here: https://cla.vmware.com/dco
And here: https://github.com/vmware/clarity/blob/master/docs/CONTRIBUTING_DEVELOPMENT.md#prerequisites

**Pull request closed without merging**
