### PR TITLE
[UX] Collapsible navigation menu scroll bug fix

### PR DESCRIPTION
**Pull request by bojan88**
Fixes issue #875

Signed-off-by: Bojan Djurdjevic <bojan88@gmail.com>

### CODE REVIEW

**Comment by youdz** [comment]
@adityarb88: Wasn't the point of the `overflow: hidden` + `:hover { overflow: scroll }` pattern (which is absolutely loathe) to not have the page jump around in some weird situation for non-Mac OS?

I just want to make sure we're not going in circles by fixing the same two bugs over and over, always negating the previous fix.

**Comment by adityarb88** [comment]
@youdz Yes that's why we added those styles. But now I think we should get rid of them because they really don't solve the issue completely plus it introduces a bug in touch devices. What do you think? I think this change looks good to me. If the content moves when the scroll bar appears, we can't do much about it in Clarity UI. Vertical Nav doesn't use this pattern.

**Comment by adityarb88** [comment]
@bojan88: Thanks for the contribution. Your name has been added to our community page: https://vmware.github.io/clarity/community

**Comment by bojan88** [comment]
My pleasure. I will try to do it more often.

**Pull request merged**
