### PR TITLE
fix(header): icons in header documentation

### PR DESCRIPTION
**Pull request by andreiconstantinbytex**
Removed header examples and code snippets that didn't fit specifications.

#3616

Signed-off-by: Andrei Constantin <andrei.constantin@bytex.ro>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3616 

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by andreiconstantinbytex** [comment]
What is a good way to approach this if Travis fails due to the fact that the images are not updated to match the current UI?

**Comment by Jinnie** [comment]
1. Check which tests are failing: `https://travis-ci.com/vmware/clarity/jobs/230290783`
2. Are they specific for the removed code, or common for the page: `common`
3. The second one is more complex, check in code what it does and is it related to the removed item: `not related`
4. Update tests and update PR: `npm run visual:fix set3`. This should generate 2 sets of updated screenshots - one for the dark theme and one for the light.
   - Prerequisite: local docker because we use a container to verify all tests are run agains the same version of Chrome browser.
   - If tests fail without reason - restart docker.

**Comment by Jinnie** [comment]
Any update on this? Need some help?

**Comment by andreiconstantinbytex** [comment]
> Any update on this? Need some help?

Hello. 
It's clear what I need to do it's just that we are experiencing some problems with our environment. The only tests that work on my machine are the unit tests so after investigating the problem I'm currently switching to Ubuntu so that Travis works as well.

**Comment by andreiconstantinbytex** [comment]
I've put back the header in the dev app. Also, fixing the header that was removed would create a duplicate example. If you would like me to add more guidance then I'll need more details.

**Comment by Jinnie** [comment]
We have the guidance up the same doc page. We clearly state that using icon only is a bad practice and we provide an illustration.

Then we break our own recommendation a few paragraphs down by providing an example with icon only menu items.

I believe that removing the wrong example is sufficient for this issue.

**Comment by Jinnie** [comment]
@andreiconstantinbytex as you reverted the dev-app changes you'll need to revert the gemini reference images too.

**Comment by Jinnie** [comment]
Hi @andreiconstantinbytex 
Please, make a final squash for your changes, so we can merge them. Thanks!

**Comment by andreiconstantinbytex** [comment]
> Hi @andreiconstantinbytex
> Please, make a final squash for your changes, so we can merge them. Thanks!

Done. Thought I already did it.

**Comment by Jinnie** [comment]
Hmm, it still reports 4 commits:
https://github.com/vmware/clarity/pull/3780/commits

**Comment by bdryanovski** [comment]
```bash
git fetch --all
git rebase -i master
```

**Comment by andreiconstantinbytex** [comment]
I'm currently trying to solve an issue that I'm experiencing locally with gemini.

**Comment by andreiconstantinbytex** [comment]
At the moment I'm unable to update this PR with the latest gemini images. The reason is the following: I rebased with the latest master and after running the fix on set3 images(npm run visual:fix:light set3 && npm run visual:fix:dark set3) I get the following error:

image

We also get this error when running ng serve. After digging into the respective .ts file I can see that the IDE indeed says it cannot find the .css because the target file is actually a .scss. After changing the import to .scss the dev app still doesn't build. What is even more peculiar is that for one engineer this works even though the import points to a nonexistent .css file and when he clicks on that import another nonexistent '.css.ts' file.

For some reason running the website app works.

**Comment by mathisscott** [comment]
@coryrylan 
Is this related to the base work that was recently merged in?

**Comment by coryrylan** [comment]
@andreiconstantinbytex Because we added a new project it needs to build at least once to generate the css artifacts. Try running `npm run build` then you should be able to run the visual fix commands.

**Comment by andreiconstantinbytex** [comment]
Thank you, @coryrylan . I managed to get the same fix from Ivan. This was indeed the issue.

**Pull request merged**
