### PR TITLE
[WEB] fix typos in CONTRIBUTING and Release Note

### PR DESCRIPTION
**Pull request by mcosta74**
I'm not sure about the change in package-lock.json but if I'm right it should report the right version

Signed-off-by: Massimo Costa <costa.massimo@gmail.com>

### CODE REVIEW

**Comment by mcosta74** [comment]
not sure about the failure detected by `netlify`

**Comment by bdryanovski** [comment]
No need to commit the `package-lock.json`

**Comment by mcosta74** [comment]
> No need to commit the `package-lock.json`

shall I change the commit in order to remove that file ??

**Comment by bdryanovski** [comment]
Yes :)

**Comment by mcosta74** [comment]
Removed the `package-lock.json` file from the commit

**Pull request merged**
