### PR TITLE
[ICONS] fix missing solid circle svg

### LINKED ISSUE #3246: Circle icon does not support is-solid class
## Describe the bug

The circle icon no longer works with 'is-solid' class.

## How to reproduce

<clr-icon shape="circle" class="is-solid is-info" size="8"></clr-icon>

1.  Add clr-icon to any project and view in browser.

## Expected behavior

The circle icon should have solid center filled with color.

## Versions

**App**

* Angular: 7.2.9
* Node: 10.14.2
* Clarity: 1.1.2

**Device:**

* Type: MacBook Pro
* OS: macOS (10.14.3)
* Browser Chrome
* Version 73.0.3683.86

## Additional notes

The circle icon supported 'is-solid' class in version 1.1.1.

### PR DESCRIPTION
**Pull request by coryrylan**
Fixes missing svg for the solid circle icon.

closes #3246

Signed-off-by: Cory Rylan <crylan@vmware.com>

### CODE REVIEW

**Comment by drourke2** [comment]
Is this fixed? I just pulled down the latest version 1.1.3 of @clr/icons and the circle still does not support solid.

**Comment by davidrourke** [comment]
In version 1.1.4 (and higher) of @clr/icons I am seeing the following error displayed in the console when referencing the solid circle icon:

Error: <path> attribute d: Unexpected end of attribute. Expected number, "…,0,0,1,18,34ZM18".

Regards,
David

**Comment by mathisscott** [comment]
@davidrourke 
[I can see the line that is giving you trouble](https://github.com/vmware/clarity/blob/bb65f19b1b57f65e1576a089b43e5a22cd0c3e35/src/clr-icons/shapes/essential-shapes.ts#L899). But I don't understand why.

That same line works just fine on the website and running locally. Can you reproduce this issue [on stackblitz](https://stackblitz.com/@clr-team)?

**Comment by davidrourke** [comment]
@mathisscott 
I could not reproduce the issue on stackblitz, but I have attached a sample application.

Regards,
David

[datagrid2.zip](https://github.com/vmware/clarity/files/3432004/datagrid2.zip)

**Pull request merged**
