### PR TITLE
Corrected class name for tooltip

### PR DESCRIPTION
**Pull request by Vad1mo**
corrected and added missing css selectors for tooltips.

### CODE REVIEW

**Comment by Vad1mo** [comment]
sorry I have no idea why @vmwclabot tell me that the commit is not signed.

**Comment by jaffoneh** [comment]
@Vad1mo: the reason the dco-bot is complaining is it looks like you're using something that is pushing this for you? The committer's email as it is shown belongs to Github:

```
"committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "date": "2016-12-30T09:42:47Z"
      },
```

You can see it here: https://api.github.com/repos/vmware/clarity/pulls/302/commits 

cc @travisfinch

**Comment by adityarb88** [comment]
Hi @Vad1mo. Could you please squash your commits and update the PR? The reason why the bot is complaining because some of your commits have `vad1mo@users.noreply.github.com` in the email field while others have `bauer.vadim@gmail.com`. After you have squashed the commits, can you please add a sign off message to the commit message like shown below:

`Signed-off-by: John Doe <john.doe@email.org>`

**Comment by adityarb88** [comment]
Hi @Vad1mo. Could you please update this PR. We would like to merge this fix in soon because the website needs to be updated with the correct classnames. Thanks again for contributing! If you are busy we could make this change and merge it in too but I will have to close this PR and create a new PR with the correct DCO.

**Comment by adityarb88** [comment]
Hi @Vad1mo. We want to merge this fix ASAP because it affects the website documentation. For now we will fix the documentation ourselves but we are happy to add you to our contributors page when you fix the `dco` issue and update this PR.

**Pull request closed without merging**
